<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="EPBYMINW1753" name="by.epam.tat.cherevach.module4.task1.unit_testing.TestSelectACar" tests="2" failures="0" timestamp="29 Nov 2015 19:38:30 GMT" time="0.000" errors="1">
  <testcase name="SelectACar" time="0.000" classname="by.epam.tat.cherevach.module4.task1.unit_testing.TestSelectACar">
    <error type="org.testng.TestException" message="
Method TestSelectACar.SelectACar(java.lang.String)[pri:0, instance:by.epam.tat.cherevach.module4.task1.unit_testing.TestSelectACar@161cd475] should have thrown an exception of type class by.epam.tat.cherevach.module3.lecture3.task1.exceptions.CarNotFoundExc">
      <![CDATA[org.testng.TestException: 
Method TestSelectACar.SelectACar(java.lang.String)[pri:0, instance:by.epam.tat.cherevach.module4.task1.unit_testing.TestSelectACar@161cd475] should have thrown an exception of type class by.epam.tat.cherevach.module3.lecture3.task1.exceptions.CarNotFoundExc
	at org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:89)
	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1381)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:681)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1246)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1171)
	at org.testng.TestNG.run(TestNG.java:1066)
	at by.epam.tat.cherevach.module4.task1.unit_testing.UnitTestRunner.main(UnitTestRunner.java:17)
]]>
    </error>
  </testcase> <!-- SelectACar -->
  <testcase name="SelectACar2" time="0.000" classname="by.epam.tat.cherevach.module4.task1.unit_testing.TestSelectACar"/>
</testsuite> <!-- by.epam.tat.cherevach.module4.task1.unit_testing.TestSelectACar -->
